export const siteContent = {
  brand: 'Remote30',
  pageTitle: 'Remote30 | A 30-day challenge for designers and developers',
  pageDescription: 'A free 30-day challenge for Nigerian designers and developers working towards international clients.',
  navigation: {
    ariaLabel: 'Main navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    links: [
      { href: '#challenge', label: 'The challenge' },
      { href: '#how-it-works', label: 'How it works' },
    ],
  },
  joinAction: 'Join the challenge',
  heroTitle: 'Finding work abroad can feel like shouting into the void.',
  heroAccent: "Let's make the next step clearer.",
  heroDescription: "You send applications. You share your work. Sometimes, nothing comes back. Remote30 is a free 30-day challenge for Nigerian designers and developers to practise explaining what they do, showing their work, and starting conversations with people who hire.",
  heroAction: 'Join the 30-day challenge',
  heroNote: "Free to join. I can't promise clients.",
  heroDetails: ['Show your work clearly', 'Start real conversations'],
  founderPhotoAlt: 'Portrait of Olajide Igbalaye, founder of Remote30',
  challengeLabel: 'The hard part',
  challengeTitle: "Good work doesn't always get noticed.",
  challengeDescription: "You can be good at your craft and still struggle to explain what you do, show the right work, or reach people who might hire you. We'll work on those parts one step at a time.",
  steps: [
    { number: '01', title: 'Make your work clear', copy: 'Say what you do, who you help, and what you can do for them.' },
    { number: '02', title: 'Show the work', copy: 'Put your best work on one page and help a stranger understand why it matters.' },
    { number: '03', title: 'Start talking', copy: 'Leave useful comments and reach out to people who hire. No copy-paste pitch.' },
  ],
  signupLabel: 'Cohort 01 starts October 1, 2026',
  signupTitle: 'Want to try this with us?',
  signupDescription: "Add your email, then join the WhatsApp group where the challenge happens. It's free. I can't promise clients, but the 30 days give you a place to practise.",
  emailFormLabel: 'Join the Remote30 challenge',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@example.com',
  emailDuplicateError: 'That email is already on the list.',
  emailFormatError: 'Please check the email address and try again.',
  emailSchemaError: 'The signup list needs an update. Please try again later.',
  emailSubmitError: "I couldn't save your email. Please try again.",
  emailSubmitLabel: 'Add my email',
  emailSubmittingLabel: 'Adding you...',
  signupSuccessTitle: "Great, I'm glad you joined us!",
  signupSuccessDescription: "Come say hello in the WhatsApp group. That's where the challenge happens.",
  signupSuccessAction: 'Join the WhatsApp group',
  signupSuccessDismiss: 'Close',
  communityLink: 'https://tinyurl.com/JoinRemote30',
  footer: 'A free 30-day challenge for Nigerian designers and developers.',
  footerNote: '30 days of practice.',
} as const

export const siteSettings = {
  colors: {
    blue: '#0B4FC4',
    darkBlue: '#0A3D9E',
    cyan: '#22E1FF',
    surface: '#F3F8FF',
  },
} as const

export type Step = (typeof siteContent.steps)[number]
